### ISSUE TITLE
Single Header for Compiler Explorer

### ISSUE THREAD

**Issue by hassec** [VcDevel/std-simd#1]
Hi,

I was wondering if there is any plan to provide a single header for use with [godbolt](https://godbolt.org/), similar to the Vc ones?

**Comment by mattkretz** [comment]
Yes, I think that's possible.

**Comment by mattkretz** [comment]
You can find a link in the Example section of README.md now. The header is in the compiler_explorer branch: toplevel `simd.h`.

**Comment by hassec** [comment]
Awesome! 
Thanks a lot :)
