### ISSUE TITLE
none_of() generates extra memory access on AVX2 in comparison to Vc 1.4

### ISSUE THREAD

**Issue by dimula73** [VcDevel/std-simd#10]
version / revision | Operating System | Compiler & Version | Compiler Flags | CPU
-------------------|------------------|--------------------|----------------|----
master (dd9a3f3c)  | Windows 10  | GCC 9.2.0 (MSYS/MinGW)  | -O2 -std=c++17  -DNDEBUG -fabi-version=0 -ffp-contract=fast -fext-numeric-literals -mavx2 | AVX2 platform

Compiler Explorer for Vc 1.4: https://godbolt.org/z/6gNtWq
Compiler Explorer for std-simd: https://godbolt.org/z/3cQHE4

## Testcase
```cpp
// std-simd code
bool compareVectors2(float *a, float *b) {
    Vc::float_v aVec(a, Vc::vector_aligned);
    Vc::float_v bVec(b, Vc::vector_aligned);

    bVec *= 2.0f;

    return none_of(aVec == bVec);
}

// Vc 1.4 code
bool compareVectors2(float *a, float *b) {
    Vc::float_v aVec(a, Vc::Aligned);
    Vc::float_v bVec(b, Vc::Aligned);

    bVec *= 2.0f;

    return (aVec == bVec).isEmpty();
}
```
## Actual Results
```asm
compareVectors2(float*, float*):
  vmovaps ymm0, YMMWORD PTR [rsi]
  vaddps ymm0, ymm0, ymm0
  vcmpeqps ymm0, ymm0, YMMWORD PTR [rdi]
  vtestps ymm0, YMMWORD PTR .LC0[rip]
  sete al
  vzeroupper
  ret
.LC0:
  .long 4294967295
  .long 4294967295
  .long 4294967295
  .long 4294967295
  .long 4294967295
  .long 4294967295
  .long 4294967295
  .long 4294967295
```
## Expected Results
```asm
compareVectors2(float*, float*):
  vmovaps ymm0, YMMWORD PTR [rsi]
  vaddps ymm0, ymm0, ymm0
  vcmpeqps ymm0, ymm0, YMMWORD PTR [rdi]
  vtestps ymm0, ymm0
  sete al
  vzeroupper
  ret
```

PS:
In general, there is something really weird happening with std-simd. I have really high register spilling in std-simd, on almost exactly the same code. I'm trying to debug it somehow, this is one of the traces I found. The other one in Vc::Zero and Vc::One constants, but it is not related to this very bug.

**Comment by mattkretz** [comment]
Thanks for the detailed report. Vc had an optimization for the testz case, where the mask doesn't have to be a full register of 1-bits but can instead be the mask that's tested. I'm applying that optimization on std-simd right now. Will push as soon as all tests are done.
