### ISSUE TITLE
bitwise reinterpretation of underlying representation 

### ISSUE THREAD

**Issue by iburyl** [VcDevel/std-simd#11]
Is there a way to bitwise reinterpret without casting of
`std::experimental::fixed_size_simd<int, 16>;`
into
`std::experimental::fixed_size_simd<float, 16>;`
or
`std::experimental::fixed_size_simd<double, 8>;`
?

**Comment by mattkretz** [comment]
[`std::bit_cast`](https://en.cppreference.com/w/cpp/numeric/bit_cast) should solve this. Or is there a specific scenario that you're thinking of that it doesn't solve?

The guarantee of `simd` to be *TriviallyCopyable* isn't written out, but I think it's implicitly there.

**Comment by iburyl** [comment]
Yes, std::bit_cast should solve my use case. Thanks.

My fear, though, is, that particular implementation may use some compiler-specific underlying data type (with its main role - to be optimized out), which may put implicit property of TriviallyCopyable on thin edge.

**Comment by mattkretz** [comment]
In principle, I want `simd<T>` to be trivial if `T` is trivial. Maybe we should put that into the wording.

**Comment by mattkretz** [comment]
mattkretz/std-simd-feedback#15

**Comment by iburyl** [comment]
Yes, thank you. I'll add my input towards the feedback issues.
