### ISSUE TITLE
Support for type traits

### ISSUE THREAD

**Issue by godefv** [VcDevel/std-simd#13]
Hi, I have not read the technical specification, but shouldn't `std::is_arithmetic<native_simd<float>>::value` be true ?

More generally, it would be nice to support <type_traits>.

**Comment by godefv** [comment]
Sorry, I have just realized that I have misunderstood what this library does.
I thought it would automatically detect what computation can be vectorized and vectorize it, by just replacing `float` by `native_simd<float>`, as is done in your example.

**Comment by mattkretz** [comment]
Your original question is still a valid question. But my understanding of `<type_traits>` is that `is_arithmetic` is supposed to reflect the languages definition of arithmetic types. Consequently, there is no room for libraries to explicitly specialize those traits. In terms of the language no user-defined type can ever be an arithmetic type - it can only behave like one.

Not sure I understand your second comment. In any case, there is no auto-vectorization in the traditional sense involved here. The software developer has to replace `T` by `native_simd<T>` and thus all operations on objects of those types are vectorized now. Does that clarify things?

**Comment by godefv** [comment]
I was looking for something which would automatically vectorize the products (a[0]*b[0], a[1]*b[1], a[2]*b[2]) in the expression for a single dot product.
I was hoping the compiler would do it, but in my case, it doesn't.
So my initial understanding was that `native_simd<T>` contained only one instance of `T`. According to cppreference, it is actually more like an aligned array of `T`s.
Therfore, I thought (wrongly) of `native_simd<float>` as a replacement of `float`. As such, and as `simd` would be part of the standard, it would have made sense that `<type_traits>` would treat `native_simd<float>` as `float`, except for std::is_simd.
