### ISSUE TITLE
MacOS - fatal error: numeric_traits.h: No such file or directory

### ISSUE THREAD

**Issue by DinosL** [VcDevel/std-simd#19]
version / revision | Operating System | Compiler & Version | Compiler Flags | CPU
-------------------|------------------|--------------------|----------------|----
       1.00                  | MacOS Catalina  | gcc version 10.2.0 (Homebrew GCC 10.2.0)|  -g0 -O2  -std=c++17 | i7-3615QM

## Testcase
I am trying to compile a dummy program just to learn a few things about vectorization. When compiling with g++-10 and the above mentioned flags, I get this error ```/usr/local/Cellar/gcc/10.2.0/include/c++/10.2.0/experimental/bits/simd.h:34:10: fatal error: numeric_traits.h: No such file or directory```. I can see that numeric_traits.h is located at ```/usr/local/Cellar/gcc/10.2.0/include/c++/10.2.0/experimental/ext ``` but I cannot find a way to link it. 

Any suggestions?

Thank you in advance

**Comment by mattkretz** [comment]
Sorry. I got distracted after starting a merge from a different repo. Will fix ASAP.

**Comment by mattkretz** [comment]
Oh wait. Are you actually using the 1.0.0 release? I guess you must have tried master, right? master should work now.

**Comment by michaelcadilhac** [comment]
Well, I do have the same problem with master (on ArchLinux, g++10.2.0); I had to do:

```diff
diff --git a/install.sh b/install.sh
index 9bac5c8..b0cf46e 100755
--- a/install.sh
+++ b/install.sh
@@ -78,6 +78,7 @@ exit 1
 
   install -v -p -d "$includedir/experimental/bits"
   install -v -p experimental/bits/simd*.h "$includedir/experimental/bits/"
+  install -v -p experimental/bits/numeric_traits.h "$includedir/experimental/bits/"
   install -v -p experimental/simd "$includedir/experimental/"
 else
   for i in experimental/bits/simd*.h experimental/simd; do
```

**Comment by mattkretz** [comment]
Oh, thanks! Fix is coming up.
