### ISSUE TITLE
Two questions for clarification

### ISSUE THREAD

**Issue by mreineck** [VcDevel/std-simd#28]
I'm sorry for posting this as an issue (which it most likely isn't), but I don't know the proper way of asking questions about the code.

I'm currently switching one of my libraries to make direct use of std::experimental::simd when available, and there are two things I can't work out for myself:

- is there a way to determine if the underlying architecture natively supports certain SIMD types? Something like
`template<typename scalar_type, int len> constexpr inline bool simd_exists;`
where, e.g. on a system with SSE2, `simd_exists<float,4>` would be `true`, but `simd_exists<float,2>` would be `false`?
- Is there an "official" way to cast a `simd` object to its underlying low-level type, like `native_simd<double>`  to `__m256d` on a machine with AVX? There are a few pretty special situations where I have to use custom functions with intrinsics for best performance.

I have tried to find the answers in the specification, but I fear I'm not good enough at standardese...

Thanks a lot, and I'm happy to continue discussion in a more suitable place if needed,
  Martin

**Comment by mreineck** [comment]
Here is an example with a horizontal sum which I think cannot be emulated with the methods in `std::experimental::simd` without losing performance:
```
// sum up vr and vi horizontally and return the result as a complex number
inline complex<float> hsum_cmplx(__m256 vr, __m256 vi)
  {
  auto t1 = _mm256_hadd_ps(vr, vi);
  auto t2 = _mm_hadd_ps(_mm256_extractf128_ps(t1, 0), _mm256_extractf128_ps(t1, 1));
  t2 += _mm_shuffle_ps(t2, t2, _MM_SHUFFLE(1,0,3,2));
  return complex<float>(t2[0], t2[1]);
  }
```

**Comment by mattkretz** [comment]
```c++
constexpr bool supports_vectors = stdx::native_simd<T>::size() > 1;
template<int N>
constexpr bool supports_vector_n = !std::is_same_v<stdx::simd<T, stdx::simd_abi::deduce_t<T, N>>, stdx::fixed_size_simd<T, N>>;
```

Casting to implementation-defined types is part of the TS specification. But, well, implementation-defined. The libstdc++ implementation defines casts to the corresponding intrinsics types (so all 16-Byte `simd<integral>` can be cast to and from `__m128i`) and the corresponding `[[gnu::vector_size(sizeof(simd<T>))]]` type. Here's an example where I show using `simd<T>` with inline asm: https://mattkretz.github.io/2019/05/27/vectorized-conversion-from-utf8-using-stdx-simd.html.

The `hsum` example cannot be implemented directly with `simd<T>`, yes. I think there's a good chance, though, that
```c++
template <typename Abi>
inline complex<float> hsum_cmplx(simd<float, Abi> vr, simd<float, Abi> vi)
  {
    return complex<float>(reduce(vr), reduce(vi));
  }
```
is not any slower and potentially even faster in terms of latency.

**Comment by mreineck** [comment]
Thank you very much, that was extremely helpful!
