### ISSUE TITLE
How to cast simd_mask of type T to another type?

### ISSUE THREAD

**Issue by torshepherd** [VcDevel/std-simd#41]
version / revision | Operating System | Compiler & Version | Compiler Flags | CPU
-------------------|------------------|--------------------|----------------|----
      GCC (trunk/all)          |      x86-64      |    GCC (trunk/all)        |  -mavx2      |

## Testcase
```cpp
using doublev = std::experimental::native_simd<double>;
using size_tv = std::experimental::rebind_simd_t<std::size_t, doublev>;

struct Bound
{
    std::vector<doublev> vals;
    std::vector<size_tv> idxs;
};

void min(Bound& a, const Bound& b) {
    for (std::size_t i = 0; i < a.vals.size(); ++i)
    {
        const auto otherIsLess = b.vals[i] < a.vals[i];
        std::experimental::where(otherIsLess, a.vals[i]) = b.vals[i];
        std::experimental::where(otherIsLess, a.idxs[i]) = b.idxs[i];
    }
}
```

## Actual Results
This code doesn't compile (https://godbolt.org/z/666G5YTqK)

## Expected Results
I couldn't find anywhere on cppreference indicating the correct pattern for this use case - how can I apply a mask to different SIMD types of different element_type's?

**Comment by mattkretz** [comment]
Well, it's an embarrassing omission in the Parallelism TS 2. The libstdc++ implementation provides two ways out:
```c++
where(otherIsLess.__cvt(), a.idxs[i]) = b.idxs[i];
```
or, the verbose variant (which, except for the `__proposed` namespace, the C++ committee would have okayed for the TS):
```c++
where(std::experimental::__proposed::static_simd_cast<typename size_tv::mask_type>(otherIsLess), a.idxs[i]) = b.idxs[i];
```

I recommend:
```c++
namespace stdx
{
  using namespace std::experimental;
  using namespace std::experimental::__proposed;
}
```
or simply use https://github.com/mattkretz/vir-simd.

I guess cppreference should discuss this issue in some form...

**Comment by mattkretz** [comment]
Added a Notes section to https://en.cppreference.com/w/cpp/experimental/simd/simd_cast.

**Comment by torshepherd** [comment]
Thank you for the response! By the way, this library is amazing. Thank you for your hard work

**Comment by ax3l** [comment]
@mattkretz Just commenting again because of https://github.com/mattkretz/vir-simd/issues/45

In application codes, I often create simd_masks from operation on floating point comparisons (i.e., range comparisons), but then operate on integer/uints with `where()`, e.g., to mark particles in a simulation.

This currently forces a conversion of the mask in C++ to work with `where`. If we could make this easier in upcoming C++ standards, e.g., through implicit support for arbitrary mask types (in terms of `T`, not size) in `where ` that does not need to match the value type of the RHS that would be wonderful and much more readable code.

**Comment by mattkretz** [comment]
I'm not 100% sure what you're looking for here.

C++26 won't have `where` anymore. It has `select(mask, t, f)`, which mimics an element-wise conditional operator (which I would overload if the language allowed).

But more importantly, every mask in C++26 is convertible to any `simd::vec<integral>` with matching size. Or potentially more interesting is unary minus on masks. For vector-masks this is typically a no-op.

The other important change is that `mask<float>` and `mask<int>` are now the same type (if they have the same size). Conversion is only necessary if the `sizeof` of the value-types differs.

**Comment by ax3l** [comment]
Thank you, I do understand this better now!

Ah, then my remaining problem is that I need to use a `select` on a `unit64_t` using a mask from a SP `float` comparison. They have the same SIMD width in elements, but don't have the same `sizeof(T)`, so I will need to convert.

For generic code: I assume a convert on already compatible types (e.g., if I started from a `double` mask in the case above) will be a no-op?

**Comment by mattkretz** [comment]
There are no guarantees on what will actually be a no-op. In general, the goal is that if it is implicitly convertible, then it is a no-op. But e.g. `mask<complex<float>, 4>` -> `mask<double, 4>` is not a no-op with AVX512¹. For some targets also explicit conversions can be no-ops (e.g. `simd::mask<double, 4>` -> `simd::mask<float, 4>` is a no-op with AVX512 bitmasks).

```c++
namespace simd = std::simd;

using floatv = simd::vec<float>;
using uint64v = simd::rebind_t<std::uint64_t, floatv>;

uint64v f(floatv x, uint64v a, uint64v b) {
  //return simd::select(x < 0, a, b); // doesn't compile because of mismatched sizeof
  auto negative = uint64v::mask_type(x < 0);
  return simd::select(negative, a, b); // OK
}
```

You could easily implement your own `lazy_select` function then, like this:
```c++
template <typename V, size_t B, typename Abi>
constexpr V lazy_select(const simd::basic_mask<B, Abi>& k, V t, V f) {
  return simd::select(static_cast<typename V::mask_type>(k), t, f);
}
```

¹ at least in the current state of my implementation

**Comment by mattkretz** [comment]
I need to clarify, because the `mask<complex<float>, 4>` -> `mask<double, 4>` issue looks surprising. But `mask` is only an alias template. And in my implementation these two will basically map to
- `basic_mask<8, InterleavedComplexWith4Elements>`
- `basic_mask<8, VecWith4Elements>`
So they are not the same type. And the current working draft says, that conversion then must be explicit.
