### ISSUE TITLE
The inline attributes are not forceful

### ISSUE THREAD

**Issue by krzikalla** [VcDevel/std-simd#47]
With `gcc 12.2 -O3` I observed performance losses when switching to std::simd, which I could attribute to inlining not having taken place.
Apparently 
```
#define _GLIBCXX_SIMD_INTRINSIC                                                \
  [[__gnu__::__always_inline__, __gnu__::__artificial__]] inline
```
is not strong enough. I have resolved it using `__attribute__((flatten))` in my user code, but maybe it is better to address this in the std::simd implementation, since inlining is absolutely crucial for this library. Unfortunately, there are a lot of competing solutions (e.g. `__attribute__((always_inline)), [[always_inline]]`) and I am unsure if anyone of these compel inlining (just to be clear: _compel_ like _really, really, 100% enforced inline_). I admit that c++ has ignored the problem for too long (as far as I am aware of it), which is why I don't have a good suggestion here.

**Comment by mattkretz** [comment]
Thanks for your feedback. Have you used this repo or the libstdc++ implementation shipping with GCC? For the latter please report issues at GCC's Bugzilla.
However,  `__attribute__((always_inline))` and `[[gnu::always_inline]]` are just two different spellings of the exact same attribute. And I've never seen a function annotated with always-inline to not be inlined, unless other attributes or recursion make inlining impossible. In which case `flatten` also doesn't help - and GCC would issue a warning.
It is rather more likely that a function you rely on is missing the attribute. With latest GCC a few issues with `fixed_size` were resolved in that area.

**Comment by mattkretz** [comment]
Ah right, GCC 12.2. The std::experimental::simd shipping with it is not "always-inline correct". Please try to upgrade your GCC / libstdc++.

**Comment by krzikalla** [comment]
> It is rather more likely that a function you rely on is missing the attribute.

It was the SIMD multiplication (perf and assembly showed it), which was of course devastating. 
But OK, if it helps to upgrade gcc then you can close this issue. Please, just keep it in mind - inlining is so important for std::simd.

**Comment by mattkretz** [comment]
Oh I know how important it is. I've seen a single `operator*` not getting inlined turning a 2x speedup into a 4x slowdown. (That was in 2009; I've been eagerly always-inlining since.)
