### ISSUE TITLE
setZero() idiom generates suboptimal code on avx512 platforms (icelake-client)

### ISSUE THREAD

**Issue by dimula73** [VcDevel/std-simd#7]
When using `where(mask, vector) = 0.0f` correct correct code is generated only on AVX2 platforms.

Godbot for AVX2 (skylake): https://godbolt.org/z/2Jqddn
Godbolt for AVX512 (icelake-client): https://godbolt.org/z/l36_Zm

## Testcase
```cpp
using float_v = std::experimental::native_simd<float>;
using int_v = std::experimental::fixed_size_simd<int32_t, float_v::size()>;


float_v f(float_v value, float_v::mask_type mask) {
    where(mask, value) = 0.0f;
    return value;
}
```

## Actual Results
```assembler
  vxorps %xmm1, %xmm1, %xmm1
  kmovw %edi, %k1
  vmovaps %zmm1, %zmm0{%k1}
```
## Expected Results
```assembler
vandnps %ymm0, %ymm1, %ymm0
```

**Comment by mattkretz** [comment]
For AVX512, the result isn't all too bad. The alternative is to use `vmovaps %zmm0, %zmm0{%k1}{z}`, but that requires `k1` to be inverted first. I.e.
```asm
  notl %edi
  kmovw %edi, %k1
  vmovaps %zmm0, %zmm0{%k1}{z}
```
If the mask had been inverted before, then this is definitely a useful optimization. Note how AVX512 uses bitmask registers and the simple "andnot" cannot work anymore. I'll try to make a useful GCC PR out of this.

**Comment by mattkretz** [comment]
https://godbolt.org/z/aPcfLa

**Comment by dimula73** [comment]
Hm, my bad, I didn't know that vandnps cannot do that anymore in AVX512. Do I understand it right that AVX512's mask has a special register type, therefore we cannot use it in normal bitwise operation?

**Comment by mattkretz** [comment]
This shows the missed optimization: https://godbolt.org/z/AmU4Yh
And well, vandnps can still do that in AVX512. But in general you want to use those special mask registers. Especially since there are no zmm compare instructions that return vector masks..

**Comment by mattkretz** [comment]
[PR93172](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93172) opened for GCC. There's nothing I can do in the library. Therefore, closing this issue.
