### ISSUE TITLE
Latest version of std-simd is 1.38x slower, potentially because of prefering partial registers on AVX512

### ISSUE THREAD

**Issue by dimula73** [VcDevel/std-simd#8]
Master version of std-simd (de882b72073e14cfd17253b007feb9d63262d24c) works 1.38x slower than a version from July (24be5a434eab86fd5dd235b18). It happens because avx512 registers are disabled in master

The picture below should explain the performance drop: Icelake has 3x256 pipelines and 2x512 pipelines. Which gives theoretical performance difference 1.33x. 

![изображение](https://user-images.githubusercontent.com/454873/68051793-53882b80-fcf9-11e9-8815-c5a1401ef9cd.png)

version / revision | Operating System | Compiler & Version | Compiler Flags | CPU
-------------------|------------------|--------------------|----------------|----
   de882b72073e14cfd17253b007feb9d63262d24c                |         Win10+MinGW         |       GCC 9.2             |  -march=icelake-client -ffixed-xmm16 -ffixed-xmm17 -ffixed-xmm18 -ffixed-xmm19 -ffixed-xmm20 -ffixed-xmm21 -ffixed-xmm22 -ffixed-xmm23 -ffixed-xmm24 -ffixed-xmm25 -ffixed-xmm26 -ffixed-xmm27 -ffixed-xmm28 -ffixed-xmm29 -ffixed-xmm30 -ffixed-xmm31              |  i7-1065G7 (Icelake) |

## Testcase
See attached zip file:
[tst-int-oct.zip](https://github.com/VcDevel/std-simd/files/3799348/tst-int-oct.zip)

## Actual Results (de882b72073e14cfd17253b007feb9d63262d24c)
Calculation finished (float): 313

## Expected Results (24be5a434eab86fd5dd235b18)
Calculation finished (float): 228

**Comment by dimula73** [comment]
Here is a patch that fixes the issue:
```
From 372736db93e61ead0240cce928d9128d981a37b3 Mon Sep 17 00:00:00 2001
From: Dmitry Kazakov <dimula73@gmail.com>
Date: Mon, 9 Dec 2019 17:55:53 +0300
Subject: [PATCH] Use 512-bit vectors if AVX512BW and AVX512VL are present

The pathch basically reverts f23d899ae261c2dac8b6ce17417d5eb193d4cd94,
which explicitly sets vector width to 256 bits on newer CPUs. I don't
know why that patch was applies, there was not comment about that.

From my benchmarks, downgrading to 256-bit vectors decreases performance
almost 1.5 times.

See bugreport: https://github.com/VcDevel/std-simd/issues/8
---
 experimental/bits/simd.h | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/experimental/bits/simd.h b/experimental/bits/simd.h
index 513a684..37b29d6 100644
--- a/experimental/bits/simd.h
+++ b/experimental/bits/simd.h
@@ -2425,9 +2425,9 @@ auto __determine_native_abi()
     return static_cast<scalar*>(nullptr);
   else if constexpr (__have_avx512bw_vl)
 #if _GLIBCXX_SIMD_X86INTRIN // {{{
-    return static_cast<_Avx512<32>*>(nullptr);
+    return static_cast<_Avx512<64>*>(nullptr);
 #else  // _GLIBCXX_SIMD_X86INTRIN
-    return static_cast<_VecBuiltin<32>*>(nullptr);
+    return static_cast<_VecBuiltin<64>*>(nullptr);
 #endif // _GLIBCXX_SIMD_X86INTRIN }}}
   else if constexpr (__have_avx512bw || (__have_avx512f && sizeof(_Tp) >= 4))
 #if _GLIBCXX_SIMD_X86INTRIN // {{{
-- 
2.23.0.windows.1


```

**Comment by mattkretz** [comment]
Thank you. I'll look into this ASAP (which might take a while because of 
upcoming vacations, sorry). I agree that the heuristic in there is wrong. I'm 
not sure what the right heuristic is. But your benchmarks lead the way for 
now.

**Comment by dimula73** [comment]
Should I make a separate merge request for that? Or this raw patch is enough?
